---@class CompileModeOpts
---
---For more info, run `:h compile-mode.default_command`
---@field default_command?          string
---
---For more info, run `:h compile-mode.time_format`
---@field time_format?              string
---
---For more info, run `:h compile-mode.buffer_name`
---@field buffer_name?              string
---
---For more info, run `:h compile-mode.error_regexp_table`
---@field error_regexp_table?       table<string, CompileModeRegexpMatcher>
---
---For more info, run `:h compile-mode.debug`
---@field debug?                    boolean
---
---For more info, run `:h compile-mode.error_ignore_file_list`
---@field error_ignore_file_list?   string[]
---
---For more info, run `:h compile-mode.hidden_output`
---@field hidden_output?            (string|string[])
---
---For more info, run `:h compile-mode.recompile_no_fail`
---@field recompile_no_fail?        boolean
---
---For more info, run `:h compile-mode.auto_jump_to_first_error`
---@field auto_jump_to_first_error? boolean
---
---For more info, run `:h compile-mode.ask_about_save`
---@field ask_about_save?           boolean
---
---For more info, run `:h compile-mode.environment`
---@field environment?              table<string| string>
---
---For more info, run `:h compile-mode.clear_environment`
---@field clear_environment?        boolean
---
---For more info, run `:h compile-mode.ask_to_interrupt`
---@field ask_to_interrupt?         boolean
---
---For more info, run `:h compile-mode.baleia_setup`
---@field baleia_setup?             boolean|table
---
---For more info, run `:h compile-mode.bang_expansion`
---@field bang_expansion?           boolean
---
---For more info, run `:h compile-mode.input_word_completion`
---@field input_word_completion?    boolean
---
---For more info, run `:h compile-mode.use_diagnostics`
---@field use_diagnostics?          boolean
---
---For more info, run `:h compile-mode.error_threshold`
---@field error_threshold?          CompileModeLevel
---
---For more info, run `:h compile-mode.error_locus_highlight`
---@field error_locus_highlight?    boolean|integer|nil
---
---For more info, run `:h compile-mode.hidden_buffer`
---@field hidden_buffer?            boolean
---
---For more info, run `:h compile-mode.use_circular_error_navigation`
---@field use_circular_error_navigation? boolean
---
---For more info, run `:h compile-mode.focus_compilation_buffer`
---@field focus_compilation_buffer? boolean
---
---For more info, run `:h compile-mode.auto_scroll`
---@field auto_scroll? boolean

---@type CompileModeOpts
vim.g.compile_mode = vim.g.compile_mode
