name: Nightly

on:
  push:
    branches:
      - main

jobs:
  nightly:
    name: Update `nightly` branch

    if: github.event.repository.fork == false

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: nightly

      - name: Pull from main
        run: |
          git fetch origin
          git merge origin/main --ff-only -m 'Sync with main'
          git push origin nightly
